### Numpy - Numerical Python

Numpy is a package

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
#load library
import numpy as np

#### the functional unit of numpy is an array
#### and an array is created from a list

In [6]:
lst = [1, 2, 3, 4, 5]

In [7]:
#creat a numpy array
lst_arr = np.array(lst)

In [10]:
lst_arr

array([1, 2, 3, 4, 5])

In [9]:
type(lst_arr)

numpy.ndarray

#### one dimensional array is called a vector, while a two_dimensional array is called a matrix

one dimensional lists are created from lists, 2-d is created from nested lists

In [12]:
nst = [[1, 2, 3], [5, 6, 7]]

In [13]:
# create a 2d-array
nst_arr = np.array(nst)

In [14]:
nst_arr

array([[1, 2, 3],
       [5, 6, 7]])

In [15]:
lst_arr.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [16]:
lst_arr.shape

(5,)

In [18]:
nst_arr.shape

(2, 3)

In [19]:
lst_arr.reshape(1,5).shape

(1, 5)

In [20]:
lst_arr

array([1, 2, 3, 4, 5])

In [35]:
tes = np.array([5, 10, 15, 20, 25])

In [36]:
lst

[1, 2, 3, 4, 5]

In [37]:
lst + lst #concatenation

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [38]:
lst_arr + tes

array([ 6, 12, 18, 24, 30])

In [4]:
yes = np.array(5)
yes

array(5)

In [44]:
nst_arr

array([[1, 2, 3],
       [5, 6, 7]])

In [45]:
nst_arr.T

array([[1, 5],
       [2, 6],
       [3, 7]])

### Numpy Indexing and slicing

In [51]:
range(0, 10, 2)

range(0, 10, 2)

In [56]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

In [6]:
list(range(0, 100, 10))

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

In [60]:
lst 

[1, 2, 3, 4, 5]

In [61]:
for i in lst:
    if i%2==1:
        print(i**2)
    else:
        print(i**3)

1
8
9
64
25


In [65]:
output = [i**2 if i%2==1 else i**3 for i in lst]

output

[1, 8, 9, 64, 25]

### Back to Numpy

In [73]:
seq = np.random.randint(0, 50, 15)
seq

array([15, 22, 18, 22, 32,  4, 34, 36, 34, 23, 17, 46, 37, 47, 14])

In [74]:
seq[::-1]

array([14, 47, 37, 46, 17, 23, 34, 36, 34,  4, 32, 22, 18, 22, 15])

In [75]:
seq[2:7]

array([18, 22, 32,  4, 34])

In [78]:
sem = seq.reshape(3,5)
sem

array([[15, 22, 18, 22, 32],
       [ 4, 34, 36, 34, 23],
       [17, 46, 37, 47, 14]])

In [79]:
sem[1,2]

36

In [82]:
sem[2,3]

47

In [83]:
sem[1,1]

34

In [84]:
sem

array([[15, 22, 18, 22, 32],
       [ 4, 34, 36, 34, 23],
       [17, 46, 37, 47, 14]])

In [85]:
sem[0:2, 1:3]

array([[22, 18],
       [34, 36]])

In [90]:
sem[1:, 3:]

array([[34, 23],
       [47, 14]])

In [91]:
type(seq)

numpy.ndarray

## Special Methods

In [92]:
seq

array([15, 22, 18, 22, 32,  4, 34, 36, 34, 23, 17, 46, 37, 47, 14])

In [93]:
#one dimensional zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [94]:
#two dimensional zeros
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [96]:
#two dimensional ones. Note that there is no "twos"
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [102]:
#random method is used to generate random numbers
#can be used to add noise to data in machine learning later
#it has lots of methods under it. press dot tab

#np.random.rand is used to generate random numbers 
#within the normal distribution betweeen 0 and 1
np.random.rand(4)

array([0.22496329, 0.05491917, 0.88977574, 0.43059913])

In [103]:
#np.random.randn is used to generate random numbers 
#within the normal distribution where 0 is the mean

np.random.randn(10)

array([-0.92354232,  0.36953477,  0.26949067, -0.14416531, -0.15247529,
       -1.15073172, -1.46072233,  0.31934111, -1.21987487,  1.32149898])

In [104]:
seq

array([15, 22, 18, 22, 32,  4, 34, 36, 34, 23, 17, 46, 37, 47, 14])

In [105]:
seq.min()

4

In [106]:
seq.max()

47

In [107]:
#index position of minimum value
seq.argmin()

5

In [108]:
#index position of maximum value
seq.argmax()

13

In [109]:
seq.mean()

26.733333333333334

In [110]:
seq.std()

11.980354288955269

In [111]:
seq.var()

143.5288888888889